image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t ragapplication_web:latest .
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker stop ragapplication_web || true
    - docker rm ragapplication_web || true
    - |
      docker run -d \
        --name ragapplication_web \
        --restart unless-stopped \
        -p 80:80 \
        ragapplication_web:latest
  only:
    - master
